
name = "DashClustergrammer"
uuid = "1b08a953-4be3-4667-9a23-a6d022159106"
authors = ["Matthew N. Bernstein <berniematt18@gmail.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compact]
julia = "1.2"
Dash = ">=0.1"
